### ISSUE TITLE
Fix completions

### ISSUE THREAD

**Issue by robb-j** [robb-j/nova-deno#1]
When typing the server is failing to generate completions. For instance adding `r` to **examples/server.ts**'s for loop, which should complete to `req` produces this error:

```txt
Unable to get completion info from TypeScript: Error: Debug Failure. Illegal value: "r"
  at isValidTrigger (deno:cli/tsc/00_typescript.js:122443:37)
  at Object.getCompletionsAtPosition (deno:cli/tsc/00_typescript.js:120179:92)
  at Object.getCompletionsAtPosition (deno:cli/tsc/00_typescript.js:149797:35)
  at serverRequest (deno:cli/tsc/99_main_compiler.js:632:27)
  at [native_code]:1:12

Internal error
```

The code:

```ts
import * as http from "https://deno.land/std@0.97.0/http/server.ts";

const server = http.serve({ port: 8000 });

console.log("http://localhost:8000/");

for await (const req of server) {
  // req.respond({ body: "Hello World\n" });
  r
}
```

**Comment by robb-j** [comment]
I requested help from deno ~ https://github.com/denoland/deno/issues/10966
and submitted a Nova bug report ~ https://devforum.nova.app/t/bug-with-textdocument-completion/969
